"""add menu to reservation

Revision ID: 9bdaa93ff612
Revises: 
Create Date: 2025-12-17 21:24:37.319295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdaa93ff612'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ① NULL 許可で追加
    with op.batch_alter_table('reservations') as batch_op:
        batch_op.add_column(
            sa.Column('menu', sa.String(length=20), nullable=True)
        )

    # ② 既存データを埋める（例：全部 training）
    op.execute(
        "UPDATE reservations SET menu = 'training' WHERE menu IS NULL"
    )

    # ③ NOT NULL 制約を付与
    with op.batch_alter_table('reservations') as batch_op:
        batch_op.alter_column(
            'menu',
            nullable=False
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('menu')

    # ### end Alembic commands ###
